env:
  jasmine: true
  amd: true
  browser: true
  es6: true
extends: 
  - 'eslint:recommended'
  - 'plugin:jasmine/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - jasmine
rules: {}